--tb_customer_integration--
/*Campo N_doc sera alterado de integer para varhcar, o campo se trata de uma PK e sera necessário criar um update para que os campos
com tamanho = 10 caracteres sejam incluidos um zero a esquerda*/
--ADCIONA COLUNA TEMPORARIA PARA REALIZAR A CONVERSÃO DOS DADOS
ALTER TABLE BNEX.TB_CUSTOMER_INTEGRATION ADD N_DOC_CHAR VARCHAR2(14);

/*LEVA OS DADOS PARA A COLUNA TEMPORARIA, USANDO A SEGUINTE REGRA CPFS COM TAMANHO <= 10 COMPLETA COM ZERO A ESQEURDA ATÉ 11 CARACTERES
CPF > 11 COMPLETA COM ZEROS A ESQUERDA ATE 14 CARACTERES CONSIDERA CPNJ
*/
UPDATE BNEX.TB_CUSTOMER_INTEGRATION
   SET N_DOC_CHAR = CASE
                      WHEN LENGTH(N_DOC) <= 10 THEN
                       LPAD(TO_CHAR(N_DOC), 11, '0')
                      WHEN LENGTH(N_DOC) > 11 THEN
                       LPAD(TO_CHAR(N_DOC), 14, '0')
                      ELSE
                       TO_CHAR(N_DOC)
                    END;

--COMANDO PARA DROPAR A PK, ASSIM CONSEGUIMOS REALIZAR O DELETE DA COLUNA
ALTER TABLE BNEX.TB_CUSTOMER_INTEGRATION DROP PRIMARY KEY;

--COMANDO PARA DROPAR A COLUNA ANTIGA
ALTER TABLE BNEX.TB_CUSTOMER_INTEGRATION DROP COLUMN N_DOC;

--RENOMEIA COLUNA NOVA
ALTER TABLE BNEX.TB_CUSTOMER_INTEGRATION RENAME COLUMN N_DOC_CHAR TO N_DOC;

--CRIA PK NOVAMENTE
ALTER TABLE BNEX.TB_CUSTOMER_INTEGRATION 
ADD CONSTRAINT PK_TB_CUSTOMER_INTEGRATION PRIMARY KEY (N_DOC);



