ALTER TABLE SENIOR.TB_STOREMATE_COLLABORATORS_HASH ADD DOCUMENT_NEW VARCHAR2(14);

UPDATE SENIOR.TB_STOREMATE_COLLABORATORS_HASH
   SET DOCUMENT_NEW = CASE
                        WHEN LENGTH(DOCUMENT) <= 10 THEN
                         LPAD(TO_CHAR(DOCUMENT), 11, '0')
                        ELSE
                         TO_CHAR(DOCUMENT)
                      END;

 ALTER TABLE SENIOR.TB_STOREMATE_COLLABORATORS_HASH DROP COLUMN DOCUMENT;

ALTER TABLE SENIOR.TB_STOREMATE_COLLABORATORS_HASH  RENAME COLUMN DOCUMENT_NEW TO DOCUMENT;