ALTER TABLE SAP.TB_STM_USUARIOS ADD CPF_N VARCHAR2(11);

UPDATE SAP.TB_STM_USUARIOS
   SET CPF_N = CASE
                 WHEN LENGTH(CPF) = 2 THEN
                  TO_CHAR(CPF)
                 ELSE
                  LPAD(TO_CHAR(CPF), 11, '0')
               END;

ALTER TABLE SAP.TB_STM_USUARIOS DROP COLUMN CPF              

ALTER TABLE SAP.TB_STM_USUARIOS RENAME COLUMN CPF_N TO CPF;

ALTER TABLE SAP.TB_STM_USUARIOS
ADD CONSTRAINT UQ_STM_USUARIOS_CPF UNIQUE (CPF);


--precisa validar apelicação