CREATE OR REPLACE FUNCTION SAP.FC_VERSAO_PESSOA(P_CPF VARCHAR2) RETURN INTEGER IS
  V_RET INTEGER;
BEGIN
  SELECT MAX(A.VERSION)
    INTO V_RET
    FROM TB_INBOUND_BP A
   WHERE A.P_O_ID_FISCAL1 = P_CPF;
  RETURN V_RET;

END;