SELECT SUBSTR(TXT_PDV, 18, 19) INTO V_CPF FROM DUAL;

S;

ALTER TABLE SISTEMAS.TB_PESSOA ADD CPF_2 VARCHAR2(14);
ALTER TABLE SISTEMAS.TB_PESSOA ADD CPF_2_TEMP VARCHAR2(14);

UPDATE SISTEMAS.TB_PESSOA A SET A.CPF_2 = TO_CHAR(A.CPF);

ALTER TABLE SISTEMAS.TB_PESSOA DROP COLUMN CPF;
ALTER TABLE SISTEMAS.TB_PESSOA RENAME COLUMN CPF_2_TEMP TO CPF;

SELECT * FROM SISTEMAS.TB_PESSOA A WHERE A.TIPO_PESSOA = 'J';

ALTER TABLE SISTEMAS.TB_PESSOA DROP COLUMN CPF_3;

ALTER TABLE SISTEMAS.TB_PESSOA ADD CONSTRAINT UQ_CPF_PESSOA UNIQUE(CPF);

SELECT COUNT(1), CPF
  FROM SISTEMAS.TB_PESSOA
HAVING COUNT(1) > 1
 GROUP BY CPF;

SELECT * FROM SISTEMAS.TB_PESSOA A WHERE CPF < 250;
;
SELECT * FROM SISTEMAS.TB_PESSOA A;

ALTER TABLE SISTEMAS.TB_OCORRENCIA DROP CONSTRAINT FK_PESSOA_OCORRENCIA;

SELECT * FROM SISTEMAS.TB_OCORRENCIA;

DECLARE
  V_CPF INTEGER := 1;
BEGIN
  FOR X IN (SELECT ID_PESSOA FROM SISTEMAS.TB_PESSOA WHERE CPF IS NULL) LOOP
    UPDATE SISTEMAS.TB_PESSOA A
       SET A.CPF = TO_CHAR(V_CPF)
     WHERE A.ID_PESSOA = X.ID_PESSOA;
  
    COMMIT;
  
    V_CPF := V_CPF + 1;
  END LOOP;
END;

SELECT *
  FROM SISTEMAS.TB_PESSOA A
 WHERE A.CPF IN (61822752868,
                 49064837805,
                 87106370878,
                 29154721814,
                 32689839873,
                 22130955827,
                 30965058883,
                 25203778280,
                 13023107807);

UPDATE SISTEMAS.TB_PESSOA A
   SET A.CPF_2_TEMP = CASE
                        WHEN A.TIPO_PESSOA = 'F' AND LENGTH(A.CPF) <= 11 THEN
                         LPAD(TO_CHAR(A.CPF), 11, '0')
                        WHEN A.TIPO_PESSOA = 'F' AND LENGTH(A.CPF) > 11 THEN
                         TO_CHAR(A.CPF)
                        ELSE
                         LPAD(TO_CHAR(A.CPF), 14, '0')
                      END;
